# Generated by Django 4.2.6 on 2023-10-18 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Secret Title')),
                ('key', models.BinaryField(verbose_name='Symmetric Key')),
                ('cipher_text', models.TextField(max_length=100000, verbose_name='Encrypted Text')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_for', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipientKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.BinaryField(verbose_name='Symmetric Key')),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_with', to='secret.secret')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_with_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
